---
site:
  title: "Configuring the system-wide cryptographic policy"
  url: https://github.com/rhpds/showroom_template_zero
  start_page: modules::01-validate.adoc

content:
  sources:
    - url: ./
      start_path: content

ui:
  bundle:
    url: https://github.com/rhpds/nookbag/releases/download/nookbag-v0.0.5/nookbag-v0.0.5.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
