---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-validate"
      label: "Validate"
    - name: "02-set"
      label: "Set"
    - name: "03-reconcile"
      label: "Reconcile"
    - name: "04-regenerate"
      label: "Regenerate"
    - name: "05-start-apache"
      label: "Start Apache"

tabs:
  - name: ">_ terminal"
    url: /wetty
